### ISSUE TITLE
Slide show ends early

### ISSUE THREAD

**Issue by jshumakerpruitt** [kentcdodds/react-jest-workshop#6]
Not sure if you have the slides and just accidentally omitted them, or if they're gone for good. The linked slide show only has a about three slides of JS related content.  'What this talk is', 'What it is not', 'Four inputs to a component'.  Maybe you have a video of the talk or a blog post?  Thanks

**Comment by jshumakerpruitt** [comment]
I see that things are pretty much self explanatory when you read the solutions in /exercises-final, but I am still curious if you have more slides, video, or a blog post.

**Comment by kentcdodds** [comment]
Unfortunately, I'm still waiting on the video recording. Perhaps @prpatel can shed some light on when it will be available...
